# Generated by Django 5.2.7 on 2025-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('cidade', models.CharField(max_length=100)),
            ],
        ),
    ]
