# Generated by Django 5.2.8 on 2025-11-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_endereco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
